settings:
  title: 'Run Status Page'
  url: 'https://status-page.runcon.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some System Issues'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Issues'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: home # unique identifier
    name: Run Construction (home)
    description: 'Main website.' # default=empty
    url: 'https://run.construction/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: portal # unique identifier
    name: Run Construction (portal)
    description: 'Frontend application, portal.' # default=empty
    url: 'https://run.construction/portal/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: learn # unique identifier
    name: Learning Center
    description: 'Training, knowledge base, etc.' # default=empty
    url: 'https://learn.run.construction/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: graphql # unique identifier
    name: GraphQL
    description: 'Backend API entrypoint.' # default=empty
    url: 'https://run.construction/api/graphql?query=query%7Bgreeting%7D' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

